name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add SECRET_KEY="$SECRET_KEY" --repo Aktama-Test/website
